---
- name: Install Zabbix Repository
  dnf:
    name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Install Zabbix Agent 2
  dnf:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix Agent
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: zabbix
    mode: '0644'
  notify: Restart Zabbix Agent

- name: Start and Enable Zabbix Agent
  service:
    name: zabbix-agent2
    state: started
    enabled: yes