apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev-team   # dev-team에만 적용
spec:
  hard:
    # [요청량 제한] 팀 전체 파드의 requests 합계
    requests.cpu: "1"        # 최대 1 Core
    requests.memory: "500Mi" # 최대 500 MB
    
    # [한도 제한] 팀 전체 파드의 limits 합계
    limits.cpu: "1"
    limits.memory: "500Mi"
    
    # [개수 제한] 파드 개수도 제한 가능 (옵션)
    pods: "5"