version: '3.5'
services:
  # 1. Zabbix Server (Core)
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    restart: always
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd

  # 2. Zabbix Web (UI)
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "80:8080"  # 외부 80포트로 접속 -> 내부 8080 연결
    restart: always
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Seoul

  # 3. Database (MariaDB)
  mysql-server:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    command: --character-set-server=utf8 --collation-server=utf8_bin