---
- name: Install Keepalived
  dnf:
    name: keepalived
    state: present

- name: Deploy Health Check Script
  template:
    src: check_db.sh.j2
    dest: /etc/keepalived/check_db.sh
    mode: '0755'  # 실행 권한 필수

- name: Deploy Keepalived Config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived

- name: Start and Enable Keepalived
  service:
    name: keepalived
    state: started
    enabled: yes